---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: my-application-ingress
  namespace: default
  labels:
    app: dmz-controller-example
  annotations:
    armesto.net/ingress-providers: vpn,office
spec:
  backend:
    serviceName: my-application-service
    servicePort: 80
