---
apiVersion: v1
kind: Service
metadata:
  name: my-application-service
  labels:
    app: dmz-controller-example
spec:
  selector:
    app: my-application
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
